# Generated by Django 3.0.8 on 2020-07-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiry_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
    ]
